// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: internal/app/proto/server.proto

package protoServer

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// StorageClient is the client API for Storage service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StorageClient interface {
	CollectMetric(ctx context.Context, in *AddMetricRequest, opts ...grpc.CallOption) (*AddMetricResponse, error)
	CollectMetrics(ctx context.Context, in *AddMetricsRequest, opts ...grpc.CallOption) (*AddMetricsResponse, error)
	GetAll(ctx context.Context, in *GetAllMetricsRequest, opts ...grpc.CallOption) (*GetAllMetricsResponse, error)
	CollectOrChangeGauge(ctx context.Context, in *CollectGaugeRequest, opts ...grpc.CallOption) (*CollectGaugeResponse, error)
	CollectOrIncreaseCounter(ctx context.Context, in *CollectCounterRequest, opts ...grpc.CallOption) (*CollectCounterResponse, error)
	GetGauge(ctx context.Context, in *GetGaugeRequest, opts ...grpc.CallOption) (*GetGaugeResponse, error)
	GetCounter(ctx context.Context, in *GetCounterRequest, opts ...grpc.CallOption) (*GetCounterResponse, error)
	PingClient(ctx context.Context, in *PingClientRequest, opts ...grpc.CallOption) (*PingClientResponse, error)
}

type storageClient struct {
	cc grpc.ClientConnInterface
}

func NewStorageClient(cc grpc.ClientConnInterface) StorageClient {
	return &storageClient{cc}
}

func (c *storageClient) CollectMetric(ctx context.Context, in *AddMetricRequest, opts ...grpc.CallOption) (*AddMetricResponse, error) {
	out := new(AddMetricResponse)
	err := c.cc.Invoke(ctx, "/app.Storage/CollectMetric", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageClient) CollectMetrics(ctx context.Context, in *AddMetricsRequest, opts ...grpc.CallOption) (*AddMetricsResponse, error) {
	out := new(AddMetricsResponse)
	err := c.cc.Invoke(ctx, "/app.Storage/CollectMetrics", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageClient) GetAll(ctx context.Context, in *GetAllMetricsRequest, opts ...grpc.CallOption) (*GetAllMetricsResponse, error) {
	out := new(GetAllMetricsResponse)
	err := c.cc.Invoke(ctx, "/app.Storage/GetAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageClient) CollectOrChangeGauge(ctx context.Context, in *CollectGaugeRequest, opts ...grpc.CallOption) (*CollectGaugeResponse, error) {
	out := new(CollectGaugeResponse)
	err := c.cc.Invoke(ctx, "/app.Storage/CollectOrChangeGauge", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageClient) CollectOrIncreaseCounter(ctx context.Context, in *CollectCounterRequest, opts ...grpc.CallOption) (*CollectCounterResponse, error) {
	out := new(CollectCounterResponse)
	err := c.cc.Invoke(ctx, "/app.Storage/CollectOrIncreaseCounter", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageClient) GetGauge(ctx context.Context, in *GetGaugeRequest, opts ...grpc.CallOption) (*GetGaugeResponse, error) {
	out := new(GetGaugeResponse)
	err := c.cc.Invoke(ctx, "/app.Storage/GetGauge", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageClient) GetCounter(ctx context.Context, in *GetCounterRequest, opts ...grpc.CallOption) (*GetCounterResponse, error) {
	out := new(GetCounterResponse)
	err := c.cc.Invoke(ctx, "/app.Storage/GetCounter", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageClient) PingClient(ctx context.Context, in *PingClientRequest, opts ...grpc.CallOption) (*PingClientResponse, error) {
	out := new(PingClientResponse)
	err := c.cc.Invoke(ctx, "/app.Storage/PingClient", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StorageServer is the server API for Storage service.
// All implementations must embed UnimplementedStorageServer
// for forward compatibility
type StorageServer interface {
	CollectMetric(context.Context, *AddMetricRequest) (*AddMetricResponse, error)
	CollectMetrics(context.Context, *AddMetricsRequest) (*AddMetricsResponse, error)
	GetAll(context.Context, *GetAllMetricsRequest) (*GetAllMetricsResponse, error)
	CollectOrChangeGauge(context.Context, *CollectGaugeRequest) (*CollectGaugeResponse, error)
	CollectOrIncreaseCounter(context.Context, *CollectCounterRequest) (*CollectCounterResponse, error)
	GetGauge(context.Context, *GetGaugeRequest) (*GetGaugeResponse, error)
	GetCounter(context.Context, *GetCounterRequest) (*GetCounterResponse, error)
	PingClient(context.Context, *PingClientRequest) (*PingClientResponse, error)
	mustEmbedUnimplementedStorageServer()
}

// UnimplementedStorageServer must be embedded to have forward compatible implementations.
type UnimplementedStorageServer struct {
}

func (UnimplementedStorageServer) CollectMetric(context.Context, *AddMetricRequest) (*AddMetricResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CollectMetric not implemented")
}
func (UnimplementedStorageServer) CollectMetrics(context.Context, *AddMetricsRequest) (*AddMetricsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CollectMetrics not implemented")
}
func (UnimplementedStorageServer) GetAll(context.Context, *GetAllMetricsRequest) (*GetAllMetricsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAll not implemented")
}
func (UnimplementedStorageServer) CollectOrChangeGauge(context.Context, *CollectGaugeRequest) (*CollectGaugeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CollectOrChangeGauge not implemented")
}
func (UnimplementedStorageServer) CollectOrIncreaseCounter(context.Context, *CollectCounterRequest) (*CollectCounterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CollectOrIncreaseCounter not implemented")
}
func (UnimplementedStorageServer) GetGauge(context.Context, *GetGaugeRequest) (*GetGaugeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGauge not implemented")
}
func (UnimplementedStorageServer) GetCounter(context.Context, *GetCounterRequest) (*GetCounterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCounter not implemented")
}
func (UnimplementedStorageServer) PingClient(context.Context, *PingClientRequest) (*PingClientResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PingClient not implemented")
}
func (UnimplementedStorageServer) mustEmbedUnimplementedStorageServer() {}

// UnsafeStorageServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StorageServer will
// result in compilation errors.
type UnsafeStorageServer interface {
	mustEmbedUnimplementedStorageServer()
}

func RegisterStorageServer(s grpc.ServiceRegistrar, srv StorageServer) {
	s.RegisterService(&Storage_ServiceDesc, srv)
}

func _Storage_CollectMetric_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddMetricRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServer).CollectMetric(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/app.Storage/CollectMetric",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServer).CollectMetric(ctx, req.(*AddMetricRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Storage_CollectMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddMetricsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServer).CollectMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/app.Storage/CollectMetrics",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServer).CollectMetrics(ctx, req.(*AddMetricsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Storage_GetAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllMetricsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServer).GetAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/app.Storage/GetAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServer).GetAll(ctx, req.(*GetAllMetricsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Storage_CollectOrChangeGauge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CollectGaugeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServer).CollectOrChangeGauge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/app.Storage/CollectOrChangeGauge",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServer).CollectOrChangeGauge(ctx, req.(*CollectGaugeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Storage_CollectOrIncreaseCounter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CollectCounterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServer).CollectOrIncreaseCounter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/app.Storage/CollectOrIncreaseCounter",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServer).CollectOrIncreaseCounter(ctx, req.(*CollectCounterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Storage_GetGauge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGaugeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServer).GetGauge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/app.Storage/GetGauge",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServer).GetGauge(ctx, req.(*GetGaugeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Storage_GetCounter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCounterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServer).GetCounter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/app.Storage/GetCounter",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServer).GetCounter(ctx, req.(*GetCounterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Storage_PingClient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingClientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServer).PingClient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/app.Storage/PingClient",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServer).PingClient(ctx, req.(*PingClientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Storage_ServiceDesc is the grpc.ServiceDesc for Storage service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Storage_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "app.Storage",
	HandlerType: (*StorageServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CollectMetric",
			Handler:    _Storage_CollectMetric_Handler,
		},
		{
			MethodName: "CollectMetrics",
			Handler:    _Storage_CollectMetrics_Handler,
		},
		{
			MethodName: "GetAll",
			Handler:    _Storage_GetAll_Handler,
		},
		{
			MethodName: "CollectOrChangeGauge",
			Handler:    _Storage_CollectOrChangeGauge_Handler,
		},
		{
			MethodName: "CollectOrIncreaseCounter",
			Handler:    _Storage_CollectOrIncreaseCounter_Handler,
		},
		{
			MethodName: "GetGauge",
			Handler:    _Storage_GetGauge_Handler,
		},
		{
			MethodName: "GetCounter",
			Handler:    _Storage_GetCounter_Handler,
		},
		{
			MethodName: "PingClient",
			Handler:    _Storage_PingClient_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/app/proto/server.proto",
}
